[package]
name = "hivemind"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.13"
rand = "0.8.5"
shakmaty = { version = "0.27.2", features = ["variant"] }
shakmaty-syzygy = "0.25.1"

[[bin]]
name = "hivemind"
path = "src/main.rs"

