[package]
name = "hivemind"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
shakmaty = { version = "0.27.2", features = ["variant"] }

[[bin]]
name = "hivemind"
path = "src/main.rs"
