[tool.poetry]
name = "hivemind"
version = "0.1.0"
description = ""
authors = ["aminwoo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
jax = {extras = ["cuda12-pip"], version = "^0.4.25"}
flax = {extras = ["all"], version = "^0.8.2"}


[[tool.poetry.source]]
name = "jax"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
