[tool.poetry]
name = "hivemind"
version = "0.1.0"
description = ""
authors = ["aminwoo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
chess = "^1.10.0"
wandb = "^0.16.6"
websocket-client = "^1.7.0"
tqdm = "^4.66.2"
pgx = {git = "git@github.com:aminwoo/pgx.git"}
tensorflow = {extras = ["and-cuda"], version = "^2.16.1"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
